# Store Sales - Preprocessing

이 노트북은 **전처리와 검증용 데이터 분할**만 담당합니다.

포함:
- `train.csv`, `test.csv`, `holidays_events.csv` 로드
- 날짜형 변환
- `store_nbr`, `family` 범주형 변환
- 시간 기준 Train / Validation 분리
- `sales`, `onpromotion` 이상치 처리 방향 정리
- Target (`sales`)의 `log1p` 변환
- `holidays` 기본 전처리
  - 날짜형 변환
  - 완전 중복 제거
  - `transferred=True`인 원래 휴일 날짜 제거
  - 정렬

제외:
- 날짜 파생 feature (`year`, `month`, `dayofweek` 등)
- `onpromotion_log`, `is_promotion`
- Holiday를 실제 매장별로 매칭하는 작업
- Lag / Rolling

위 항목들은 **Feature Engineering** 단계에서 처리합니다.

# Store Sales - Preprocessing

이 노트북은 **전처리와 검증용 데이터 분할**을 담당합니다. 위에서부터 순서대로 실행하세요.

포함:
- train, test, holidays, oil, transactions 로드·날짜형 변환
- 판매 데이터 크리스마스 누락 행 복원 → 범주형 변환 → 시간 기준 분할
- 이상치 유지 방침, Target log1p, Holiday 기본 정리
- Oil 일별 날짜 복원·시간 기반 보간·첫날 대체
- Transactions 크리스마스·2016-01-01·2016-01-03 보완
- 보완값 표시·처리 방법 기록·최종 품질 검사

제외: EDA 그래프, 날짜/Promotion 피처, Holiday 매장 매칭, Lag/Rolling, 모델 학습.

**Oil의 전체 기간 보간 결과는 과거 기록 복원용입니다. 모델에는 아직 병합하지 않습니다.** 실제 예측 시점을 재현할 때 쓸 Fold 기준 과거값 대체 함수도 별도로 제공합니다. 거래량 보완값 역시 실측값이 아닙니다.

## 1. 라이브러리·데이터 경로

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
from IPython.display import display

cwd = Path.cwd()
if (cwd / "data").is_dir():
    DATA_DIR = cwd / "data"
elif (cwd.parent / "data").is_dir():
    DATA_DIR = cwd.parent / "data"
else:
    raise FileNotFoundError("data 폴더를 찾을 수 없습니다.")
print("DATA_DIR:", DATA_DIR)

DATA_DIR: c:\projects\Store Sales-ML\data

## 2. 데이터 로드·원본 보존

In [2]:
def load_data(data_dir):
    return (
        pd.read_csv(data_dir / "train.csv"),
        pd.read_csv(data_dir / "test.csv"),
        pd.read_csv(data_dir / "holidays_events.csv"),
        pd.read_csv(data_dir / "oil.csv"),
        pd.read_csv(data_dir / "transactions.csv"),
    )

train_raw, test_raw, holidays_raw, oil_raw, transactions_raw = load_data(DATA_DIR)
train = train_raw.copy()
test = test_raw.copy()
holidays = holidays_raw.copy()
oil = oil_raw.copy()
transactions = transactions_raw.copy()

for name, df in [("train", train), ("test", test), ("holidays", holidays),
                 ("oil", oil), ("transactions", transactions)]:
    df["date"] = pd.to_datetime(df["date"], errors="raise")
    if df["date"].isna().any():
        raise ValueError(f"{name}: 날짜 결측")
    print(name, df.shape, df["date"].dtype)

train (3000888, 6) datetime64[us]
test (28512, 5) datetime64[us]
holidays (350, 6) datetime64[us]
oil (1218, 2) datetime64[us]
transactions (83488, 3) datetime64[us]

## 3. 판매 데이터 크리스마스 복원

4년간 누락된 크리스마스를 휴점일로 가정해 sales·onpromotion을 0으로 보완합니다. **분할 전에 복원**하여 train_df에도 반영되게 합니다. 기존 키는 추가하지 않고, 기존 보완 표시도 보존합니다.

`id=-1`은 복원 행의 임시값입니다. 중복 검사는 id가 아닌 날짜×매장×상품군으로 합니다.

In [3]:
def restore_sales_christmas(df):
    df = df.copy()
    keys = ["date", "store_nbr", "family"]
    if df.duplicated(keys).any():
        raise ValueError("판매 데이터에 중복 키가 있습니다.")
    if "is_added_missing_date" not in df:
        df["is_added_missing_date"] = 0
    christmas_dates = pd.to_datetime([
        "2013-12-25", "2014-12-25", "2015-12-25", "2016-12-25"
    ])
    christmas_dates = christmas_dates[
        (christmas_dates >= df["date"].min())
        & (christmas_dates <= df["date"].max())
    ]
    rows = pd.MultiIndex.from_product(
        [christmas_dates, sorted(df["store_nbr"].unique()),
         sorted(df["family"].unique())], names=keys
    ).to_frame(index=False)
    old_keys = pd.MultiIndex.from_frame(df[keys])
    new_keys = pd.MultiIndex.from_frame(rows[keys])
    rows = rows.loc[~new_keys.isin(old_keys)].copy()
    rows["sales"] = 0.0
    rows["onpromotion"] = 0
    rows["is_added_missing_date"] = 1
    rows["id"] = -1
    result = pd.concat([df, rows], ignore_index=True)
    result = result.sort_values(keys).reset_index(drop=True)
    return result, len(rows)

train, sales_added_count = restore_sales_christmas(train)
print("이번 추가된 판매 행:", sales_added_count)
print("누적 복원 행:", train["is_added_missing_date"].sum())

이번 추가된 판매 행: 7128
누적 복원 행: 7128

## 4. 범주형 변수 처리

행을 합친 뒤 범주형을 확정합니다. Train/Test에 같은 범주 목록을 적용합니다.

In [4]:
def convert_categories(df, category_types):
    df = df.copy()
    for col, dtype in category_types.items():
        df[col] = df[col].astype(dtype)
    return df

category_types = {
    col: pd.CategoricalDtype(
        categories=sorted(set(train[col].dropna()) | set(test[col].dropna()))
    )
    for col in ["store_nbr", "family"]
}
train = convert_categories(train, category_types)
test = convert_categories(test, category_types)
test = test.sort_values(["date", "store_nbr", "family"]).reset_index(drop=True)
print(train[["store_nbr", "family"]].dtypes)

store_nbr    category
family       category
dtype: object

## 5. Train / Validation Split

마지막 16일을 검증에 사용합니다.
- Train: 2013-01-01 ~ 2017-07-30
- Validation: 2017-07-31 ~ 2017-08-15
- Test: 2017-08-16 ~ 2017-08-31

여기서는 단일 검증 분할만 생성합니다. 여러 Fold 반복은 모델 실험 단계에서 수행합니다.

In [5]:
def split_train_valid(train, valid_days=16):
    valid_start = train["date"].max() - pd.Timedelta(days=valid_days - 1)
    train_df = train.loc[train["date"] < valid_start].copy()
    valid_df = train.loc[train["date"] >= valid_start].copy()
    return train_df, valid_df

train_df, valid_df = split_train_valid(train)
for name, df in [("Train", train_df), ("Valid", valid_df), ("Test", test)]:
    print(name, df["date"].min(), "~", df["date"].max(), df.shape)

Train 2013-01-01 00:00:00 ~ 2017-07-30 00:00:00 (2979504, 7)
Valid 2017-07-31 00:00:00 ~ 2017-08-15 00:00:00 (28512, 7)
Test 2017-08-16 00:00:00 ~ 2017-08-31 00:00:00 (28512, 5)

## 6. 이상치 처리 방향

sales: IQR 기반 일괄 제거는 정상적인 고판매량까지 제거할 수 있으므로 원본 관측값을 유지합니다.

onpromotion: 높은 값도 실제 프로모션 정보일 수 있으므로 일괄 삭제하지 않습니다. 위에서 추가한 휴점 가정 행만 0으로 보완합니다.

## 7. Target 로그 변환

원본 sales는 보존하고 sales_log를 추가합니다. onpromotion_log는 Feature Engineering에서 처리합니다.

In [6]:
def add_target_log(df):
    df = df.copy()
    if df["sales"].isna().any() or (df["sales"] < 0).any():
        raise ValueError("sales 결측 또는 음수 확인 필요")
    df["sales_log"] = np.log1p(df["sales"])
    return df

train_df = add_target_log(train_df)
valid_df = add_target_log(valid_df)
print("sales 왜도:", train_df["sales"].skew())
print("sales_log 왜도:", train_df["sales_log"].skew())

sales 왜도: 7.401918945884069
sales_log 왜도: 0.4147814665362639

## 8. Holiday 기본 전처리

완전히 같은 행만 제거하고 transferred=True인 원래 날짜를 제외합니다. 실제 이동된 휴일인 type="Transfer"는 별도로 일괄 삭제하지 않습니다. 같은 날짜의 서로 다른 지역 이벤트는 유지하며 매장 매칭·병합은 하지 않습니다.

In [7]:
def preprocess_holidays(holidays):
    holidays = holidays.copy().drop_duplicates()
    holidays = holidays.loc[holidays["transferred"].eq(False)].copy()
    return holidays.sort_values(
        ["date", "locale", "locale_name"]
    ).reset_index(drop=True)

holidays = preprocess_holidays(holidays)
print("정리 후 Holiday:", holidays.shape)
print(holidays["transferred"].value_counts())
display(holidays.head())

정리 후 Holiday: (338, 6)
transferred
False    338
Name: count, dtype: int64

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

## 9. Oil 전처리 — 전체 기간의 과거 기록 복원

일별 날짜를 생성하고 양쪽 관측값이 있는 구간만 시간 기반 선형 보간합니다. 첫날은 기존 결정대로 바로 다음 날 값으로 대체합니다. 첫날 대체 코드는 한 번만 실행합니다.

`is_imputed`와 `imputation_method`는 보완 여부·방법을 기록합니다. 미래 관측을 참조하므로 **oil_clean을 무조건 모델에 병합하지 않습니다.** 원본 oil은 별도로 보존합니다.

In [8]:
def preprocess_oil(oil):
    df = oil[["date", "dcoilwtico"]].copy()
    df["date"] = pd.to_datetime(df["date"], errors="raise")
    if df["date"].isna().any() or df["date"].duplicated().any():
        raise ValueError("Oil 날짜 결측 또는 중복")
    df = df.sort_values("date").set_index("date").asfreq("D")
    missing = df["dcoilwtico"].isna()
    df["imputation_method"] = np.where(missing, "unresolved", "observed")
    df["dcoilwtico"] = df["dcoilwtico"].interpolate(
        method="time", limit_area="inside"
    )
    df.loc[missing & df["dcoilwtico"].notna(), "imputation_method"] = "time_interpolation"
    if pd.isna(df["dcoilwtico"].iloc[0]) and len(df) > 1:
        next_value = df["dcoilwtico"].iloc[1]
        if pd.notna(next_value):
            df.loc[df.index[0], "dcoilwtico"] = next_value
            df.loc[df.index[0], "imputation_method"] = "next_day_copy"
    df["is_imputed"] = (missing & df["dcoilwtico"].notna()).astype("int8")
    print("날짜 복원 후 보간 전 결측:", int(missing.sum()))
    print("보완 후 결측:", int(df["dcoilwtico"].isna().sum()))
    return df.reset_index()

oil_clean = preprocess_oil(oil)
display(oil_clean.head(10))
display(oil_clean["imputation_method"].value_counts())

날짜 복원 후 보간 전 결측: 529
보완 후 결측: 0

        date  dcoilwtico   imputation_method  is_imputed
0 2013-01-01   93.140000       next_day_copy           1
1 2013-01-02   93.140000            observed           0
2 2013-01-03   92.970000            observed           0
3 2013-01-04   93.120000            observed           0
4 2013-01-05   93.146667  time_interpolation           1
5 2013-01-06   93.173333  time_interpolation           1
6 2013-01-07   93.200000            observed           0
7 2013-01-08   93.210000            observed           0
8 2013-01-09   93.080000            observed           0
9 2013-01-10   93.810000            observed           0

imputation_method
observed              1175
time_interpolation     528
next_day_copy            1
Name: count, dtype: int64

## 10. Transactions 전처리

- 크리스마스 4일: 휴점 가정에 따라 0
- 2016-01-01: 25번 매장은 2016-01-02 관측값, 나머지 매장은 0
- 2016-01-03: 과거 네 일요일의 매장별 중앙값
- 일요일 유효 관측이 하나도 없으면 직전 28일 중앙값으로 Fallback

Fallback에는 이미 보완한 크리스마스·1월 1일 값도 포함됩니다. 기존 관측값은 덮어쓰지 않고 결측만 대체합니다. 추정값에 소수가 있을 수 있으며 반올림하지 않습니다. 다른 날짜의 모든 누락 매장 조합을 일괄 생성하거나 0으로 채우지 않습니다.

1월 1일 대체 정책은 EDA의 당일 판매 기록 및 다음 날 거래량에 근거합니다. 당일 예측 입력으로 바로 사용할 수 있다는 뜻은 아닙니다.

In [9]:
def preprocess_transactions(transactions, store_ids):
    df = transactions[["date", "store_nbr", "transactions"]].copy()
    df["date"] = pd.to_datetime(df["date"], errors="raise")
    keys = ["date", "store_nbr"]
    if df[keys].isna().any().any() or df.duplicated(keys).any():
        raise ValueError("Transactions 키 결측 또는 중복")
    df["transactions"] = df["transactions"].astype(float)
    df["is_imputed"] = 0
    df["imputation_method"] = np.where(
        df["transactions"].notna(), "observed", "unresolved"
    )
    original_count = len(df)
    dates = pd.date_range(df["date"].min(), df["date"].max(), freq="D")
    christmas_dates = dates[(dates.month == 12) & (dates.day == 25)]
    special_dates = pd.to_datetime(["2016-01-01", "2016-01-03"])
    special_dates = special_dates[
        (special_dates >= dates.min()) & (special_dates <= dates.max())
    ]
    target_dates = christmas_dates.union(special_dates)
    rows = pd.MultiIndex.from_product(
        [target_dates, sorted(store_ids)], names=keys
    ).to_frame(index=False)
    existing_keys = pd.MultiIndex.from_frame(df[keys])
    new_keys = pd.MultiIndex.from_frame(rows[keys])
    rows = rows.loc[~new_keys.isin(existing_keys)].copy()
    rows["transactions"] = np.nan
    rows["is_imputed"] = 0
    rows["imputation_method"] = "unresolved"
    df = pd.concat([df, rows], ignore_index=True)

    # 크리스마스: 결측만 0으로 보완
    mask = df["date"].isin(christmas_dates) & df["transactions"].isna()
    df.loc[mask, "transactions"] = 0.0
    df.loc[mask, "imputation_method"] = "christmas_zero"
    df.loc[mask, "is_imputed"] = 1

    # 1월 1일 25번 매장: 바로 다음 날의 거래량
    mask_25 = (df["date"].eq(pd.Timestamp("2016-01-01"))
               & df["store_nbr"].eq(25) & df["transactions"].isna())
    if mask_25.any():
        next_values = df.loc[
            df["date"].eq(pd.Timestamp("2016-01-02")) & df["store_nbr"].eq(25),
            "transactions",
        ].dropna()
        if len(next_values) != 1:
            raise ValueError("1월 2일 25번 매장 관측값을 하나로 확인할 수 없습니다.")
        df.loc[mask_25, "transactions"] = next_values.iloc[0]
        df.loc[mask_25, "imputation_method"] = "next_day_copy"
        df.loc[mask_25, "is_imputed"] = 1

    mask_other = (df["date"].eq(pd.Timestamp("2016-01-01"))
                  & df["store_nbr"].ne(25) & df["transactions"].isna())
    df.loc[mask_other, "transactions"] = 0.0
    df.loc[mask_other, "imputation_method"] = "new_year_zero"
    df.loc[mask_other, "is_imputed"] = 1

    # 1월 3일: 과거 일요일 중앙값 → 최근 28일 중앙값
    target_date = pd.Timestamp("2016-01-03")
    past_sundays = [target_date - pd.Timedelta(weeks=i) for i in range(1, 5)]
    sunday_median = (
        df.loc[df["date"].isin(past_sundays)]
        .groupby("store_nbr")["transactions"].median()
    )
    recent_median = (
        df.loc[(df["date"] >= target_date - pd.Timedelta(days=28))
               & (df["date"] < target_date)]
        .groupby("store_nbr")["transactions"].median()
    )
    mask_jan3 = df["date"].eq(target_date) & df["transactions"].isna()
    ids = df.loc[mask_jan3, "store_nbr"]
    sunday_values = ids.map(sunday_median)
    values = sunday_values.fillna(ids.map(recent_median))
    methods = pd.Series("unresolved", index=ids.index)
    methods.loc[sunday_values.notna()] = "past_4_sundays_median"
    methods.loc[sunday_values.isna() & values.notna()] = "recent_28d_median"
    df.loc[mask_jan3, "transactions"] = values
    df.loc[mask_jan3, "imputation_method"] = methods
    df.loc[mask_jan3, "is_imputed"] = values.notna().astype(int)
    df["is_imputed"] = df["is_imputed"].astype("int8")
    df = df.sort_values(keys).reset_index(drop=True)
    print("원본 행 수:", original_count)
    print("추가 행 수:", len(rows))
    print("최종 행 수:", len(df))
    return df

# 함수는 원본 transactions에서 매번 새로 계산하므로 셀 재실행 시 중복되지 않음
transactions_filled = preprocess_transactions(
    transactions, train["store_nbr"].dropna().unique()
)
display(transactions_filled["imputation_method"].value_counts())
display(transactions_filled.loc[
    transactions_filled["is_imputed"].eq(1)
].groupby("date").size().rename("보완 행 수"))
display(transactions_filled.loc[
    transactions_filled["date"].isin(pd.to_datetime(["2016-01-01", "2016-01-03"]))
])

원본 행 수: 83488
추가 행 수: 324
최종 행 수: 83812

imputation_method
observed                 83488
christmas_zero             216
new_year_zero               53
past_4_sundays_median       53
next_day_copy                1
recent_28d_median            1
Name: count, dtype: int64

date
2013-12-25    54
2014-12-25    54
2015-12-25    54
2016-01-01    54
2016-01-03    54
2016-12-25    54
Name: 보완 행 수, dtype: int64

            date  store_nbr  transactions  is_imputed      imputation_method
52554 2016-01-01          1           0.0           1          new_year_zero
52555 2016-01-01          2           0.0           1          new_year_zero
52556 2016-01-01          3           0.0           1          new_year_zero
52557 2016-01-01          4           0.0           1          new_year_zero
52558 2016-01-01          5           0.0           1          new_year_zero
...          ...        ...           ...         ...                    ...
52693 2016-01-03         50        3293.0           1  past_4_sundays_median
52694 2016-01-03         51        2003.5           1  past_4_sundays_median
52695 2016-01-03         52           0.0           1      recent_28d_median
52696 2016-01-03         53        1010.0           1  past_4_sundays_median
52697 2016-01-03         54        1166.5           1  past_4_sundays_median

[108 rows x 5 columns]

## 11. 예측 시점용 Oil 처리 — 전체 보간 결과와 구분

아래 함수는 **원본 oil에서 cutoff 이후 관측값을 먼저 제외**한 뒤 일별 시간축에 ffill합니다. 검증 기간에도 cutoff까지의 마지막 관측값만 이어 씁니다. 첫 관측 이전에는 과거 값이 없으므로 NaN을 유지합니다.

이는 실제 예측 시점을 재현하는 한 가지 대체 정책이며, 위의 oil_clean을 변경하지 않습니다. 여러 Fold에서는 cutoff·end_date를 각 Fold에 맞춰 다시 호출해야 합니다. 여기의 검사는 이 함수가 cutoff 이후 유가를 쓰지 않는지만 확인하며 전체 모델 파이프라인의 무누수를 보장하지 않습니다.

In [10]:
def make_oil_asof(oil, cutoff, end_date):
    cutoff, end_date = pd.Timestamp(cutoff), pd.Timestamp(end_date)
    if end_date < cutoff:
        raise ValueError("end_date는 cutoff 이후여야 합니다.")
    raw = oil[["date", "dcoilwtico"]].copy()
    raw["date"] = pd.to_datetime(raw["date"], errors="raise")
    if raw["date"].isna().any() or raw["date"].duplicated().any():
        raise ValueError("Oil 날짜 결측 또는 중복")
    raw = raw.loc[raw["date"] <= cutoff].sort_values("date")
    if raw.empty:
        raise ValueError("cutoff 이전 데이터가 없습니다.")
    raw = raw.set_index("date")
    calendar = pd.date_range(raw.index.min(), end_date, freq="D", name="date")
    daily = raw.reindex(calendar)
    source_dates = pd.Series(daily.index, index=daily.index).where(
        daily["dcoilwtico"].notna()
    )
    daily["source_date"] = source_dates.ffill()
    daily["dcoilwtico"] = daily["dcoilwtico"].ffill()
    assert daily["source_date"].dropna().le(cutoff).all()
    return daily.reset_index()

fold_cutoff = train_df["date"].max()
oil_fold_safe = make_oil_asof(oil, fold_cutoff, valid_df["date"].max())
print("Fold 학습 종료일:", fold_cutoff)
display(oil_fold_safe.loc[oil_fold_safe["date"] >= fold_cutoff])
print("첫 관측 이전의 남은 결측:", oil_fold_safe["dcoilwtico"].isna().sum())

Fold 학습 종료일: 2017-07-30 00:00:00

           date  dcoilwtico source_date
1671 2017-07-30       49.72  2017-07-28
1672 2017-07-31       49.72  2017-07-28
1673 2017-08-01       49.72  2017-07-28
1674 2017-08-02       49.72  2017-07-28
1675 2017-08-03       49.72  2017-07-28
1676 2017-08-04       49.72  2017-07-28
1677 2017-08-05       49.72  2017-07-28
1678 2017-08-06       49.72  2017-07-28
1679 2017-08-07       49.72  2017-07-28
1680 2017-08-08       49.72  2017-07-28
1681 2017-08-09       49.72  2017-07-28
1682 2017-08-10       49.72  2017-07-28
1683 2017-08-11       49.72  2017-07-28
1684 2017-08-12       49.72  2017-07-28
1685 2017-08-13       49.72  2017-07-28
1686 2017-08-14       49.72  2017-07-28
1687 2017-08-15       49.72  2017-07-28

첫 관측 이전의 남은 결측: 1

## 12. 최종 품질 검사

Sales 기대 복원 행은 7,128개, Transactions 기대 추가 행은 324개(최종 83,812행)입니다. 이는 원본 대회 파일 기준 기대값이며 아래 실행 출력으로 확인합니다.

전체 기록이 없는 날짜가 0개여도 모든 날짜×매장 조합이 존재한다는 뜻은 아닙니다. 추정값 표시·방법 컬럼은 추적용이며 자동으로 모델 입력에 포함하지 않습니다.

In [11]:
def check_table(name, df, keys, value_cols, require_daily=True):
    assert pd.api.types.is_datetime64_any_dtype(df["date"]), f"{name}: 날짜형 오류"
    assert not df[keys + value_cols].isna().any().any(), f"{name}: 결측 남음"
    assert not df.duplicated(keys).any(), f"{name}: 중복 키"
    assert df[keys].reset_index(drop=True).equals(
        df.sort_values(keys)[keys].reset_index(drop=True)
    ), f"{name}: 정렬 오류"
    for col in value_cols:
        assert np.isfinite(df[col].to_numpy(dtype=float)).all(), f"{name}/{col}: 비유한 값"
        assert df[col].ge(0).all(), f"{name}/{col}: 음수"
    dates = pd.date_range(df["date"].min(), df["date"].max(), freq="D")
    missing = dates.difference(pd.DatetimeIndex(df["date"].unique()))
    if require_daily:
        assert len(missing) == 0, f"{name}: 전체 누락 날짜 {missing.tolist()}"
    print(name, "QC 통과 | 행 수:", len(df), "| 전체 누락 날짜:", len(missing))

sales_keys = ["date", "store_nbr", "family"]
check_table("Train 전체", train, sales_keys, ["sales", "onpromotion"])
check_table("Train", train_df, sales_keys, ["sales", "sales_log", "onpromotion"])
check_table("Valid", valid_df, sales_keys, ["sales", "sales_log", "onpromotion"])
check_table("Test", test, sales_keys, ["onpromotion"])
check_table("Oil 복원본", oil_clean, ["date"], ["dcoilwtico"])
check_table("Transactions", transactions_filled, ["date", "store_nbr"], ["transactions"])
assert train_df["date"].max() < valid_df["date"].min()
assert valid_df["date"].max() < test["date"].min()
assert valid_df["date"].nunique() == 16
assert test["date"].nunique() == 16
assert not holidays.duplicated().any()
assert holidays["transferred"].eq(False).all()

# 보완 표시가 있는 행에 값과 방법이 모두 존재하는지 확인
for name, df, col in [("Oil", oil_clean, "dcoilwtico"),
                      ("Transactions", transactions_filled, "transactions")]:
    estimated = df["is_imputed"].eq(1)
    assert df.loc[estimated, col].notna().all()
    assert not df["imputation_method"].eq("unresolved").any()
    print(name, "보완값 수:", int(estimated.sum()))

print("판매 데이터 누적 복원 행:", int(train["is_added_missing_date"].sum()))
print("Transactions 원본 대비 추가 행:", len(transactions_filled) - len(transactions))
print("모든 검사 완료")

Train 전체 QC 통과 | 행 수: 3008016 | 전체 누락 날짜: 0
Train QC 통과 | 행 수: 2979504 | 전체 누락 날짜: 0
Valid QC 통과 | 행 수: 28512 | 전체 누락 날짜: 0
Test QC 통과 | 행 수: 28512 | 전체 누락 날짜: 0
Oil 복원본 QC 통과 | 행 수: 1704 | 전체 누락 날짜: 0
Transactions QC 통과 | 행 수: 83812 | 전체 누락 날짜: 0
Oil 보완값 수: 529
Transactions 보완값 수: 324
판매 데이터 누적 복원 행: 7128
Transactions 원본 대비 추가 행: 324
모든 검사 완료

## 다음 단계: Feature Engineering

- 날짜·Promotion 피처 생성
- stores를 이용한 Holiday의 National/Regional/Local 매장 매칭
- Lag/Rolling 등 과거 기반 피처
- Oil·Transactions 피처를 각 Fold에서 이용 가능한 시점에 맞춰 생성·병합

`transactions_filled`의 같은 날 거래량을 미래 16일 예측 입력으로 바로 사용하지 않습니다. 1월 1일 매장 25의 값은 1월 2일 정보를 참조하므로 해당 값의 가용 시점도 고려해야 합니다. Kaggle에서 제공된 미래 외부 데이터를 활용하는 실험과 실제 미래 예측 재현 실험은 구분해 기록합니다.

`oil_fold_safe`의 첫 관측 이전 NaN은 미래값으로 채우지 않습니다. 이 결측을 모델에서 처리하는 방법은 모델 입력 설계 단계에서 정합니다.

In [12]:
from pathlib import Path

import numpy as np
import pandas as pd

from IPython.display import display

## 1. 데이터 경로 설정

In [13]:
cwd = Path.cwd()

if (cwd / "data").exists():
    DATA_DIR = cwd / "data"
elif (cwd.parent / "data").exists():
    DATA_DIR = cwd.parent / "data"
else:
    raise FileNotFoundError("data 폴더를 찾을 수 없습니다.")

print("DATA_DIR:", DATA_DIR)

DATA_DIR: c:\projects\Store Sales-ML\data

## 2. 데이터 로드

In [14]:
def load_data():
    train = pd.read_csv(DATA_DIR / "train.csv")
    test = pd.read_csv(DATA_DIR / "test.csv")
    holidays = pd.read_csv(DATA_DIR / "holidays_events.csv")

    return train, test, holidays


train, test, holidays = load_data()

print("train   :", train.shape)
print("test    :", test.shape)
print("holidays:", holidays.shape)

train   : (3000888, 6)
test    : (28512, 5)
holidays: (350, 6)

## 3. 날짜형 변환

In [15]:
train["date"] = pd.to_datetime(train["date"])
test["date"] = pd.to_datetime(test["date"])
holidays["date"] = pd.to_datetime(holidays["date"])

print("train date dtype   :", train["date"].dtype)
print("test date dtype    :", test["date"].dtype)
print("holidays date dtype:", holidays["date"].dtype)

train date dtype   : datetime64[us]
test date dtype    : datetime64[us]
holidays date dtype: datetime64[us]

## 4. 범주형 변수 처리

In [16]:
def convert_categories(df):
    df = df.copy()

    df["store_nbr"] = df["store_nbr"].astype("category")
    df["family"] = df["family"].astype("category")

    return df


train = convert_categories(train)
test = convert_categories(test)

print(train[["store_nbr", "family"]].dtypes)

store_nbr    category
family       category
dtype: object

## 5. Train / Validation Split

실제 Kaggle test가 **16일**이므로, 학습 데이터의 마지막 16일을 validation으로 사용합니다.

- Train: 2013-01-01 ~ 2017-07-30
- Validation: 2017-07-31 ~ 2017-08-15
- Test: 2017-08-16 ~ 2017-08-31

In [17]:
def split_train_valid(train, valid_days=16):
    valid_start = train["date"].max() - pd.Timedelta(days=valid_days - 1)

    train_df = train[train["date"] < valid_start].copy()
    valid_df = train[train["date"] >= valid_start].copy()

    return train_df, valid_df


train_df, valid_df = split_train_valid(train)

print("Train:", train_df["date"].min(), "~", train_df["date"].max())
print("Valid:", valid_df["date"].min(), "~", valid_df["date"].max())
print("Test :", test["date"].min(), "~", test["date"].max())

print()
print("Train shape:", train_df.shape)
print("Valid shape:", valid_df.shape)
print("Test shape :", test.shape)

Train: 2013-01-01 00:00:00 ~ 2017-07-30 00:00:00
Valid: 2017-07-31 00:00:00 ~ 2017-08-15 00:00:00
Test : 2017-08-16 00:00:00 ~ 2017-08-31 00:00:00

Train shape: (2972376, 6)
Valid shape: (28512, 6)
Test shape : (28512, 5)

## 6. 이상치 처리 방향

EDA 및 전처리 분석 결과:

### `sales`
- IQR 기준으로 제거하면 정상적인 고판매량까지 너무 많이 제거됨
- 상위 극단값이 주로 `GROCERY I`, `BEVERAGES` 등 고판매 상품군에 집중됨
- 따라서 **극단값을 일괄 삭제하지 않음**

### `onpromotion`
- 높은 값이 특정 기간에 반복적으로 나타남
- 전체적으로 `sales`와 양의 상관관계가 확인됨
- 따라서 **극단값을 일괄 삭제하지 않음**

현재 단계에서는 `sales`, `onpromotion` 모두 원본 데이터를 유지합니다.

## 7. Target 변환

`sales`는 강한 right-skew를 보였고 `log1p` 적용 후 왜도가 크게 감소했습니다.

- 원본 `sales`는 보존
- 모델링용 target 후보로 `sales_log = log1p(sales)` 추가

`onpromotion_log`는 feature이므로 여기서는 만들지 않습니다.

In [18]:
def add_target_log(df):
    df = df.copy()
    df["sales_log"] = np.log1p(df["sales"])
    return df


train_df = add_target_log(train_df)
valid_df = add_target_log(valid_df)

print("sales skew")
print("original:", train_df["sales"].skew())
print("log1p   :", train_df["sales_log"].skew())

sales skew
original: 7.393602284266503
log1p   : 0.4112816327259582

## 8. Holiday 구조 확인

Holiday는 같은 날짜에도 `National`, `Regional`, `Local` 등이 동시에 존재할 수 있으므로  
**날짜만 기준으로 중복 제거하면 안 됩니다.**

먼저 원본 구조를 확인합니다.

In [19]:
print("Holiday columns:")
print(holidays.columns.tolist())

print("\nType counts:")
print(holidays["type"].value_counts())

print("\nLocale counts:")
print(holidays["locale"].value_counts())

print("\nTransferred counts:")
print(holidays["transferred"].value_counts())

display(holidays.head(20))

Holiday columns:
['date', 'type', 'locale', 'locale_name', 'description', 'transferred']

Type counts:
type
Holiday       221
Event          56
Additional     51
Transfer       12
Bridge          5
Work Day        5
Name: count, dtype: int64

Locale counts:
locale
National    174
Local       152
Regional     24
Name: count, dtype: int64

Transferred counts:
transferred
False    338
True      12
Name: count, dtype: int64

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False
5,2012-05-12,Holiday,Local,Puyo,Cantonizacion del Puyo,False
6,2012-06-23,Holiday,Local,Guaranda,Cantonizacion de Guaranda,False
7,2012-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
8,2012-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
9,2012-06-25,Holiday,Local,Machala,Fundacion de Machala,False
10,2012-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
11,2012-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
12,2012-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
13,2012-08-05,Holiday,Local,Esmeraldas,Fundacion de Esmeraldas,False
14,2012-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,False
15,2012-08-15,Holiday,Local,Riobamba,Fundacion de Riobamba,False
16,2012-08-24,Holiday,Local,Ambato,Fundacion de Ambato,False
17,2012-09-28,Holiday,Local,Ibarra,Fundacion de Ibarra,False
18,2012-10-07,Holiday,Local,Quevedo,Cantonizacion de Quevedo,False
19,2012-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True

## 9. Holiday 기본 전처리

여기서는 **Holiday 자체를 정리하는 전처리만** 수행합니다.

- `date`는 이미 `datetime`으로 변환됨
- 완전히 동일한 행만 제거
- `transferred=True`인 원래 휴일 날짜는 제거
  - 실제 이동된 휴일 날짜는 데이터의 `type="Transfer"` 행으로 별도 존재할 수 있으므로 삭제하지 않음
- 날짜/적용 범위 기준으로 정렬

아직 `train/test`에 merge하지 않습니다.  
`National / Regional / Local`을 실제 매장에 적용하려면 `stores.csv`의 `city`, `state` 정보가 필요하므로 Feature Engineering 단계에서 처리합니다.

In [20]:
def preprocess_holidays(holidays):
    holidays = holidays.copy()

    # 완전히 동일한 행만 제거
    holidays = holidays.drop_duplicates()

    # 원래 날짜에서 실제 휴일로 적용되지 않는 transferred=True 제거
    holidays = holidays[
        holidays["transferred"] == False
    ].copy()

    # 정렬 및 index 정리
    holidays = (
        holidays
        .sort_values(["date", "locale", "locale_name"])
        .reset_index(drop=True)
    )

    return holidays


holidays = preprocess_holidays(holidays)

print("Preprocessed holidays shape:", holidays.shape)
print("\nTransferred counts after preprocessing:")
print(holidays["transferred"].value_counts())

display(holidays.head(20))

Preprocessed holidays shape: (338, 6)

Transferred counts after preprocessing:
transferred
False    338
Name: count, dtype: int64

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False
5,2012-05-12,Holiday,Local,Puyo,Cantonizacion del Puyo,False
6,2012-06-23,Holiday,Local,Guaranda,Cantonizacion de Guaranda,False
7,2012-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
8,2012-06-25,Holiday,Local,Machala,Fundacion de Machala,False
9,2012-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
10,2012-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
11,2012-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
12,2012-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
13,2012-08-05,Holiday,Local,Esmeraldas,Fundacion de Esmeraldas,False
14,2012-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,False
15,2012-08-15,Holiday,Local,Riobamba,Fundacion de Riobamba,False
16,2012-08-24,Holiday,Local,Ambato,Fundacion de Ambato,False
17,2012-09-28,Holiday,Local,Ibarra,Fundacion de Ibarra,False
18,2012-10-07,Holiday,Local,Quevedo,Cantonizacion de Quevedo,False
19,2012-10-12,Transfer,National,Ecuador,Traslado Independencia de Guayaquil,False

## 10. 같은 날짜에 여러 Holiday가 존재하는지 확인

같은 날짜에 여러 행이 남아 있는 것은 반드시 중복 오류가 아닙니다.  
서로 다른 지역 범위의 Holiday가 동시에 존재할 수 있기 때문입니다.

In [21]:
holiday_date_counts = (
    holidays
    .groupby("date")
    .size()
    .sort_values(ascending=False)
)

display(holiday_date_counts.head(20))

date
2014-06-25    4
2017-06-25    3
2012-06-25    3
2013-06-25    3
2015-06-25    3
2016-06-25    3
2012-12-22    2
2013-05-12    2
2017-07-03    2
2012-12-24    2
2012-07-03    2
2014-07-03    2
2014-12-22    2
2012-12-31    2
2013-07-03    2
2013-12-22    2
2014-12-26    2
2015-07-03    2
2015-12-22    2
2016-04-21    2
dtype: int64

## 11. 최종 확인

In [22]:
print("train_df:", train_df.shape)
print("valid_df:", valid_df.shape)
print("test    :", test.shape)
print("holidays:", holidays.shape)

print("\ntrain_df columns:")
print(train_df.columns.tolist())

print("\nholidays columns:")
print(holidays.columns.tolist())

train_df: (2972376, 7)
valid_df: (28512, 7)
test    : (28512, 5)
holidays: (338, 6)

train_df columns:
['id', 'date', 'store_nbr', 'family', 'sales', 'onpromotion', 'sales_log']

holidays columns:
['date', 'type', 'locale', 'locale_name', 'description', 'transferred']

In [23]:
full_dates = pd.date_range(
    train["date"].min(),
    train["date"].max(),
    freq="D"
)

missing_dates = full_dates.difference(
    train["date"].drop_duplicates()
)

print("Missing dates:", len(missing_dates))
print(missing_dates)

Missing dates: 4
DatetimeIndex(['2013-12-25', '2014-12-25', '2015-12-25', '2016-12-25'], dtype='datetime64[us]', freq=None)

In [24]:
holidays[
    holidays["date"].isin(missing_dates)
].sort_values("date")

          date     type    locale locale_name description  transferred
87  2013-12-25  Holiday  National     Ecuador     Navidad        False
152 2014-12-25  Holiday  National     Ecuador     Navidad        False
205 2015-12-25  Holiday  National     Ecuador     Navidad        False
288 2016-12-25  Holiday  National     Ecuador     Navidad        False

## 다음 단계: Feature Engineering

다음 단계에서는 새로운 모델 입력 변수를 만듭니다.

### 날짜 Feature
- `year`
- `month`
- `day`
- `dayofweek`
- `is_weekend`

### Promotion Feature
- `onpromotion_log`
- `is_promotion`

### Holiday Feature
`stores.csv`를 이용해 각 Holiday가 실제로 적용되는 store를 판단합니다.

- National → 모든 매장
- Regional → 해당 `state`의 매장
- Local → 해당 `city`의 매장

이후 `date × store_nbr` 단위로 Holiday 정보를 정리해 `train/valid/test`에 merge합니다.

### 시계열 Feature
- Lag
- Rolling
- 과거 판매 0 비율 등

sales 결측치 처리

In [25]:
full_dates = pd.date_range(
    train["date"].min(),
    train["date"].max(),
    freq="D"
)

In [26]:
missing_dates = full_dates.difference(
    train["date"].drop_duplicates()
)

print("Missing dates:", len(missing_dates))
print(missing_dates)

Missing dates: 4
DatetimeIndex(['2013-12-25', '2014-12-25', '2015-12-25', '2016-12-25'], dtype='datetime64[us]', freq=None)

In [27]:
# 빠진 크리스마스 날짜
missing_dates = pd.to_datetime([
    "2013-12-25",
    "2014-12-25",
    "2015-12-25",
    "2016-12-25"
])

# 모든 매장과 상품군
stores = train["store_nbr"].unique()
families = train["family"].unique()

# 날짜 × 매장 × 상품군의 모든 조합 생성
missing_rows = pd.MultiIndex.from_product(
    [missing_dates, stores, families],
    names=["date", "store_nbr", "family"]
).to_frame(index=False)

# 휴점일로 판단하여 0으로 복원
missing_rows["sales"] = 0.0
missing_rows["onpromotion"] = 0

# 원본에는 없는 행임을 표시
missing_rows["is_added_missing_date"] = 1

# id는 원본 Kaggle id가 없으므로 임시값
missing_rows["id"] = -1


# 기존 데이터는 실제 관측값
train["is_added_missing_date"] = 0


# 컬럼 순서 통일
missing_rows = missing_rows[
    [
        "id",
        "date",
        "store_nbr",
        "family",
        "sales",
        "onpromotion",
        "is_added_missing_date"
    ]
]


# 원본 train에 추가
train = pd.concat(
    [train, missing_rows],
    ignore_index=True
)


# 날짜 → 매장 → 상품군 순으로 정렬
train = train.sort_values(
    ["date", "store_nbr", "family"]
).reset_index(drop=True)

In [28]:
missing_dates = full_dates.difference(
    train["date"].drop_duplicates()
)

print("Missing dates:", len(missing_dates))
print(missing_dates)

Missing dates: 0
DatetimeIndex([], dtype='datetime64[us]', freq='D')